-- TODO

INSERT INTO COMPANY (ID, INN)
values (1, 10),
       (2, 20);

INSERT INTO MODEL (ID, DESCR)
VALUES (1, 'DESCRIPTION');

INSERT INTO MODEL_CALC (MODEL_ID, NODE, PARENT_NODE, WEIGHT, LEVEL, IS_LEAF)
values (1, 2, 3, 4, 5, 1)
