-- TODO
delete
from COMPANIES;
delete
from FORMULAS;
DELETE
from RULES;
delete
from MODEL_CALC;
delete
from MODELS;


INSERT INTO COMPANIES (ID, INN)
values (1, 10),
       (2, 20);

INSERT INTO MODELS (ID, NAME)
VALUES (1, 'Model 1'),
       (2, 'Model 2');

INSERT INTO MODEL_CALC (MODEL_ID, NODE, PARENT_NODE, WEIGHT, LEVEL, IS_LEAF)
values (1, 2, 3, 4, 5, 1);

INSERT INTO rules (ID, NAME, MODEL_ID)
VALUES (1, 'rule 1', '1');
INSERT into FORMULAS (NODE, NAME, CALCULATION, FORMULA_TYPE, A, B, C, D, XB, COMMENTS, RULE_ID)
VALUES (1, 'Formula 1', 'calc', 'type', 'A', 'B', 'C', 'D', 'XB', 'Comm', 1);
INSERT INTO BUSINESS_PARAMS (PARAM_CODE, DESCRIPTION)
VALUES (10, 'Code 10');
INSERT INTO FORMULA_PARAMS (NODE, PARAM_CODE)
VALUES (1, 10);

INSERT INTO COMPANY_BUSINESS_PARAMS (COMPANY_ID, PARAM_CODE, YEAR, PARAM_VALUE)
VALUES (1, 10, 2000, 'Val');