package ru.mifi.constructor.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ru.mifi.constructor.model.ModelCalc;
import ru.mifi.constructor.repository.ConstructorMapper;

import java.util.Random;

@Service
public class ModelCalcService {

    @Autowired
    ConstructorMapper constructorMapper;

    @Transactional
    public void updateModelCalc(ModelCalc modelCalc) {
        constructorMapper.updateModelCalc(modelCalc);
    }

    @Transactional
    public void createModelCalc(ModelCalc modelCalc) {
//        TODO node =? (id) must be autogenerated
//        modelCalc.setId(new Random().nextInt() + "");
        constructorMapper.createModelCalc(modelCalc);
    }

    @Transactional
    public void deleteModelCalc(String id) {
        constructorMapper.deleteModelCalc(id);
    }
}
