package ru.mifi.constructor.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ru.mifi.constructor.model.DTO.ModelDTO;
import ru.mifi.constructor.model.Model;
import ru.mifi.constructor.repository.CompanyMapper;
import ru.mifi.service.risk.domain.Formula;

import javax.validation.Valid;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

@Service
public class ConstructorService {

    @Autowired
    CompanyMapper companyMapper;

    public List<ModelDTO> getAllModelsDTO() throws SQLException {
        List<Model> allModels = companyMapper.getAllModels();
        List<ModelDTO> allModelsDTO = new ArrayList<>();
        for (Model model : allModels) {
            allModelsDTO.add(new ModelDTO(model));
        }
        return allModelsDTO;
    }

    public List<Model> getAllModels() throws SQLException {
        return companyMapper.getAllModels();
    }

    @Transactional
    public void updateFormula(Formula formula) {
        companyMapper.updateFormula(formula);
    }

    @Transactional
    public void createFormula(Formula formula) {
//        TODO node =? (id) must be autogenerated
        formula.setNode("2");
        companyMapper.createFormula(formula);
    }
}
