package ru.mifi.constructor.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ru.mifi.constructor.model.DTO.ModelDTO;
import ru.mifi.constructor.model.DTO.TreeNodeDTO;
import ru.mifi.constructor.model.Model;
import ru.mifi.constructor.repository.ConstructorMapper;
import ru.mifi.service.risk.domain.Formula;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

@Service
public class ModelService {

    @Autowired
    ConstructorMapper constructorMapper;

    public List<ModelDTO> getAllModelsDTO() throws SQLException {
        List<Model> allModels = constructorMapper.getAllModels();
        List<ModelDTO> allModelsDTO = new ArrayList<>();
        for (Model model : allModels) {
            allModelsDTO.add(new ModelDTO(model));
        }
        return allModelsDTO;
    }

    public List<Model> getAllModels() throws SQLException {
        return constructorMapper.getAllModels();
    }


    @Transactional
    public void updateModel(Model model) {
        constructorMapper.updateModel(model);
    }

    @Transactional
    public void createModel(Model model) {
//        TODO node =? (id) must be autogenerated
        model.setId(new Random().nextInt() + "");
        constructorMapper.createModel(model);
    }

    @Transactional
    public void deleteModel(String id) {
        constructorMapper.deleteModel(id);
    }

    public List<TreeNodeDTO> getAllTreeNodeDTOs() throws SQLException {
        List<Formula> allFormulas = constructorMapper.getAllFormulas();
        List<Model> allModels = getAllModels();
        TreeNodeDTO treeNodeDTO = new TreeNodeDTO(allModels,allFormulas);

        return treeNodeDTO.getResultList();
    }
}
