package ru.mifi.constructor.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ru.mifi.constructor.model.Model;
import ru.mifi.constructor.repository.ConstructorMapper;

import java.util.Random;

@Service
public class ModelService {

    @Autowired
    ConstructorMapper constructorMapper;

    @Transactional
    public void updateModel(Model model) {
        constructorMapper.updateModel(model);
    }

    @Transactional
    public void createModel(Model model) {
//        TODO node =? (id) must be autogenerated
        model.setId(new Random().nextInt() + "");
        constructorMapper.createModel(model);
    }

    @Transactional
    public void deleteModel(String id) {
        constructorMapper.deleteModel(id);
    }
}
