package ru.mifi.constructor.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ru.mifi.constructor.model.Rule;
import ru.mifi.constructor.repository.ConstructorMapper;

import java.util.Random;

@Service
public class RuleService {

    @Autowired
    ConstructorMapper constructorMapper;

    @Transactional
    public void updateRule(Rule rule) {
        constructorMapper.updateRule(rule);
    }

    @Transactional
    public void createRule(Rule rule) {
//        TODO node =? (id) must be autogenerated
        rule.setId(new Random().nextInt() + "");
        constructorMapper.createRule(rule);
    }

    @Transactional
    public void deleteRule(String id) {
        constructorMapper.deleteRule(id);
    }
}
